#import <ReactNativeCheckBiometricAuthChangedSpec/ReactNativeCheckBiometricAuthChangedSpec.h>

@interface ReactNativeCheckBiometricAuthChanged : NSObject <NativeReactNativeCheckBiometricAuthChangedSpec>

@end
